### ISSUE TITLE
-t type option

### ISSUE THREAD

**Issue by linuxcaffe** [shushcat/taskgv#2]
taskgv.py currently maps project <--> task, and task <--> tag.

I think it would be extra-good to also map dependencies too, 
but what if you didn't want to map all that?

New cli-option -t could be used like so;

taskgv.py (no type option, show all possible connections)
taskgv.py -t proj (just proj <--> task)
taskgv.py -t tag (just task <--> tag)
taskgv.py -t dep (just task dependencies)

These types could also reduce the selection to relevant tasks, 
ie. if a task has no tags, it is not shown when using -t tag.

**Comment by shushcat** [comment]
If I'm understanding this correclty, it's functionality that's already available with Taskwarrior and -- by extension -- to taskgv.
